name: Metrics

on:
  schedule: 
    - cron: "0 2 * * SUN"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-slim

    permissions:
      contents: write

    steps:
      - uses: gh-metrics/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: EDM115
          template: classic

          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          repositories_forks: yes

          committer_message: Update ${filename} [skip ci]
          config_octicon: yes
          config_timezone: Europe/Paris
          optimize: css, svg, xml
          experimental_features: --optimize-svg

          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C

          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_timestamps: yes
          plugin_activity_visibility: public

          plugin_discussions: yes
          plugin_discussions_categories: yes

          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_indepth: yes
          plugin_followup_sections: repositories, user

          plugin_gists: yes

          plugin_habits: yes
          plugin_habits_charts: yes
          plugin_habits_charts_type: graph
          plugin_habits_days: 14
          plugin_habits_facts: yes
          plugin_habits_from: 200
          plugin_habits_languages_limit: 0
          plugin_habits_languages_threshold: 0%
          plugin_habits_trim: yes

          plugin_introduction: yes
          plugin_introduction_title: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_colors: github
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_indepth: true
          plugin_languages_limit: 0
          plugin_languages_other: yes
          plugin_languages_recent_categories: data, markup, programming, prose
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base, repositories, history

          plugin_music: yes
          plugin_music_limit: 5
          plugin_music_mode: recent
          plugin_music_played_at: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_time_range: short
          plugin_music_top_type: tracks
          plugin_music_user: .user.login

          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: .user.website

          plugin_reactions: yes
          plugin_reactions_details: count, percentage
          plugin_reactions_display: absolute
          plugin_reactions_limit: 300

          plugin_repositories: yes
          plugin_repositories_pinned: 6

          plugin_sponsors: yes
          plugin_sponsors_sections: goal, list
          plugin_sponsors_title: Sponsor me :)

          plugin_sponsorships: yes

          plugin_stackoverflow: yes
          plugin_stackoverflow_limit: 3
          plugin_stackoverflow_lines: 2
          plugin_stackoverflow_lines_snippet: 2
          plugin_stackoverflow_sections: answers-top, questions-recent
          plugin_stackoverflow_user: 18644204

          plugin_stargazers: yes
          plugin_stargazers_charts: yes
          plugin_stargazers_charts_type: graph
          plugin_stargazers_days: 0

          plugin_steam: yes
          plugin_steam_achievements_limit: 5
          plugin_steam_games_limit: 5
          plugin_steam_recent_games_limit: 5
          plugin_steam_token: ${{ secrets.STEAM_API_KEY }}
          plugin_steam_user: 76561199401264474

          plugin_traffic: yes

          plugin_wakatime: yes
          plugin_wakatime_days: 30
          plugin_wakatime_languages_other: yes
          plugin_wakatime_limit: 5
          plugin_wakatime_repositories_visibility: public
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
